version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - ext
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super_secret_root_password
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      TZ: Asia/Bangkok

  adminer:
    image: adminer
    command: php -S 0.0.0.0:8080 -t /var/www/html
    ports:
      - 8082:8080
    networks:
      - ext
    restart: always

networks:
  ext:
    name: ext-network
    external: true
    
