version: '3.7'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 8081:81
      - 443:443
    volumes:
      - ./certs/data:/data
      - ./certs/letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: 'true'
      TZ: Asia/Bangkok
    networks:
      - ext

networks:
  ext:
    name: ext-network
    external: true